import json
import unicodedata
from typing import Any, Dict

from backend.models.song import Song


# ---------- helpers (safe casting) ----------
def _to_float(v: Any) -> float | None:
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _to_int(v: Any) -> int | None:
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def _normalize_text(v: Any) -> str | None:
    if not v:
        return None
    return unicodedata.normalize("NFC", str(v)).strip()


# ---------- ETL core ----------
def load_playlist_etl(json_path: str, session) -> None:
    """
    One-time ETL for Alembic (SYNC):
    Pivoted JSON -> row-wise -> songs table

    - Uses external_id for idempotency
    - Internal id (INT) auto-generated by DB
    """
    with open(json_path, "r", encoding="utf-8") as f:
        data: Dict[str, Dict[str, Any]] = json.load(f)

    total_rows = max(len(col) for col in data.values())

    for i in range(total_rows):
        row = {k: v.get(str(i)) for k, v in data.items()}

        external_id = row.get("id")
        if not external_id:
            continue

        exists = (
            session.query(Song)
            .filter(Song.external_id == external_id)
            .first()
        )
        if exists:
            continue

        title = _normalize_text(row.get("title"))
        duration_ms = _to_int(row.get("duration_ms"))

        song = Song(
            external_id=external_id,
            title=title,
            title_lower=title.lower() if title else None,
            danceability=_to_float(row.get("danceability")),
            energy=_to_float(row.get("energy")),
            loudness=_to_float(row.get("loudness")),
            acousticness=_to_float(row.get("acousticness")),
            tempo=_to_float(row.get("tempo")),
            duration_ms=duration_ms,
            duration_seconds=(duration_ms / 1000) if duration_ms else None,
            num_sections=_to_int(row.get("num_sections")),
            num_segments=_to_int(row.get("num_segments")),
            rating=None,
        )

    try:
        session.add(song)
        session.commit()
    except Exception:
        session.rollback()
        raise