"""create songs table

Revision ID: 32318348d9fa
Revises: 
Create Date: 2025-12-14 18:57:49.671979

"""
from pathlib import Path
from typing import Sequence, Union
from sqlalchemy.orm import Session
from backend.etl.loader import load_playlist_etl

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32318348d9fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    BASE_DIR = Path(__file__).resolve().parents[2]
    DATA_FILE = BASE_DIR / "backend" / "data" / "song_playlist.json"

    load_playlist_etl(str(DATA_FILE), session)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
